# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: leotran <leotran@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/13 05:10:00 by leotran           #+#    #+#              #
#    Updated: 2021/06/13 06:08:05 by leotran          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-2

SOURCE = ./srcs/*.c

HEADER = ./includes/

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SOURCE) -I$(HEADER)

fclean:
	rm -f $(NAME)